use rand::{distr::Uniform, Rng};
use sha2::{Digest, Sha256};

pub fn generate_random_password() -> String {
    // Define the character set, including letters, digits, underscores, and hyphens
    let charset: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ\
                           abcdefghijklmnopqrstuvwxyz\
                           0123456789_-";
    let mut rng = rand::rng();
    let dist = Uniform::try_from(0..charset.len()).expect("failed to sample values between bounds");

    // Generate a random string of 32 characters
    (0..32).map(|_| charset[rng.sample(dist)] as char).collect()
}

pub fn sha256(data: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data.as_bytes());
    hex::encode(hasher.finalize())
}

pub fn double_sha256(data: &str) -> String {
    let first_hash = sha256(data);
    sha256(&first_hash)
}

fn hex_to_base36(byte: u8) -> char {
    let res_byte = match byte / 7 {
        byte @ 0..=9 => byte + b'0',
        byte @ 10..=35 => byte + b'a' - 10,
        36 => b'e',
        _ => unreachable!(),
    };
    res_byte as char
}

pub fn make_v2_address(key: &str, address_prefix: &str) -> String {
    let mut protein = [0u8; 9];
    let mut used = [false; 9];
    let mut chain = String::from(address_prefix);
    let mut hash = double_sha256(key);

    for i in 0..9 {
        protein[i] = u8::from_str_radix(&hash[0..2], 16).unwrap();
        hash = double_sha256(&hash);
    }

    let mut i = 0;
    while i < 9 {
        let start = 2 * i;
        let end = start + 2;
        let hex_part = &hash[start..end];
        let num = u8::from_str_radix(hex_part, 16).unwrap();
        let index = (num % 9) as usize;

        if used[index] {
            hash = sha256(&hash);
        } else {
            chain.push(hex_to_base36(protein[index]));
            used[index] = true;
            i += 1;
        }
    }

    chain
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_known_values() {
        assert_eq!(make_v2_address("test123", "k"), "krcgbmalxg");
        assert_eq!(make_v2_address("0", "k"), "kzbdy8rmok");
        assert_eq!(make_v2_address("1", "k"), "k4om3ewezk");
        assert_eq!(make_v2_address("2", "k"), "kd18lv0b6u");
        assert_eq!(make_v2_address("3", "k"), "krdfu99fep");
        assert_eq!(make_v2_address("4", "k"), "k8kl0fyol5");
        assert_eq!(make_v2_address("5", "k"), "kl996ygs97");
        assert_eq!(make_v2_address("6", "k"), "k926k4tgmh");
        assert_eq!(make_v2_address("7", "k"), "k6o8rgjqi2");
        assert_eq!(make_v2_address("8", "k"), "knvvk3kahp");
        assert_eq!(make_v2_address("9", "k"), "kv2k3ja3o9");
        assert_eq!(make_v2_address("10", "k"), "kg2z1gkjeg");
        assert_eq!(make_v2_address("11", "k"), "ks5mt33gqi");
        assert_eq!(make_v2_address("12", "k"), "k33y72rso6");
        assert_eq!(make_v2_address("13", "k"), "kcn5gneqv2");
        assert_eq!(make_v2_address("14", "k"), "keb6t9aco7");
        assert_eq!(make_v2_address("15", "k"), "kocw4j8k78");
        assert_eq!(make_v2_address("16", "k"), "k078bqpep3");
        assert_eq!(make_v2_address("17", "k"), "kvi4a7nchd");
        assert_eq!(make_v2_address("18", "k"), "k844zur73f");
        assert_eq!(make_v2_address("19", "k"), "k9m9k6rqnb");
        assert_eq!(make_v2_address("20", "k"), "k7epvkaby3");
        assert_eq!(make_v2_address("21", "k"), "knjeifn0w6");
        assert_eq!(make_v2_address("22", "k"), "k2cv4rqoug");
        assert_eq!(make_v2_address("23", "k"), "kx6swd5wwa");
        assert_eq!(make_v2_address("24", "k"), "ka1lpdcpdr");
        assert_eq!(make_v2_address("25", "k"), "k1pnlhya7a");
        assert_eq!(make_v2_address("26", "k"), "kl73sw5pex");
        assert_eq!(make_v2_address("27", "k"), "k99fewvpn3");
        assert_eq!(make_v2_address("28", "k"), "ksecyo9ngd");
        assert_eq!(make_v2_address("29", "k"), "kynvm3ww04");
        assert_eq!(make_v2_address("30", "k"), "kpv2ejrqde");
        assert_eq!(make_v2_address("31", "k"), "kyz0g2pazn");
        assert_eq!(make_v2_address("32", "k"), "k9vhqs581z");
        assert_eq!(make_v2_address("33", "k"), "kk7v8cb91v");
        assert_eq!(make_v2_address("34", "k"), "ki3ovb3mdn");
        assert_eq!(make_v2_address("35", "k"), "kot7hmac5w");
        assert_eq!(make_v2_address("36", "k"), "k53nvecvu4");
        assert_eq!(make_v2_address("37", "k"), "kpk8g73vp2");
        assert_eq!(make_v2_address("38", "k"), "kqyqydzs0z");
        assert_eq!(make_v2_address("39", "k"), "k845sq35vi");
        assert_eq!(make_v2_address("40", "k"), "km72jjsckh");
        assert_eq!(make_v2_address("41", "k"), "k92e46l4uu");
        assert_eq!(make_v2_address("42", "k"), "kely98lteo");
        assert_eq!(make_v2_address("43", "k"), "ktob2xk3yo");
        assert_eq!(make_v2_address("44", "k"), "k2blzqle5x");
        assert_eq!(make_v2_address("45", "k"), "kxgzg8uqh3");
        assert_eq!(make_v2_address("46", "k"), "kokk797ysj");
        assert_eq!(make_v2_address("47", "k"), "k4g76mq7vu");
        assert_eq!(make_v2_address("48", "k"), "komooksbso");
        assert_eq!(make_v2_address("49", "k"), "kc0ffp9rlx");
        assert_eq!(make_v2_address("50", "k"), "kut3galmy8");
        assert_eq!(make_v2_address("51", "k"), "kmj81mt541");
        assert_eq!(make_v2_address("52", "k"), "kipgxehdej");
        assert_eq!(make_v2_address("53", "k"), "k6wmmy8p93");
        assert_eq!(make_v2_address("54", "k"), "kozr0b2e0y");
        assert_eq!(make_v2_address("55", "k"), "kmt4afs3wu");
        assert_eq!(make_v2_address("56", "k"), "kbixxdo4c2");
        assert_eq!(make_v2_address("57", "k"), "kduj8a4ldd");
        assert_eq!(make_v2_address("58", "k"), "k6wsrzqlik");
        assert_eq!(make_v2_address("59", "k"), "koh164xfrz");
        assert_eq!(make_v2_address("60", "k"), "k007y25fzg");
        assert_eq!(make_v2_address("61", "k"), "kbsve28q1u");
        assert_eq!(make_v2_address("62", "k"), "kgybn7m4i1");
        assert_eq!(make_v2_address("63", "k"), "k5vtxj8s3k");
        assert_eq!(make_v2_address("64", "k"), "kcnu7qz4w6");
        assert_eq!(make_v2_address("65", "k"), "kplnfpth76");
        assert_eq!(make_v2_address("66", "k"), "kfwmv7r9b9");
        assert_eq!(make_v2_address("67", "k"), "kbe0cf2f4u");
        assert_eq!(make_v2_address("68", "k"), "kh6ebimtjo");
        assert_eq!(make_v2_address("69", "k"), "k55r8j0i3m");
        assert_eq!(make_v2_address("70", "k"), "k272e1prqi");
        assert_eq!(make_v2_address("71", "k"), "kzrj91zw6s");
        assert_eq!(make_v2_address("72", "k"), "koofavuwl9");
        assert_eq!(make_v2_address("73", "k"), "kn9sogm537");
        assert_eq!(make_v2_address("74", "k"), "kkfgmdrizf");
        assert_eq!(make_v2_address("75", "k"), "kevvmui6h2");
        assert_eq!(make_v2_address("76", "k"), "kwwcsof23u");
        assert_eq!(make_v2_address("77", "k"), "kldt9so5ud");
        assert_eq!(make_v2_address("78", "k"), "kmxrax6loj");
        assert_eq!(make_v2_address("79", "k"), "ksdvseio41");
        assert_eq!(make_v2_address("80", "k"), "kbj08gxue5");
        assert_eq!(make_v2_address("81", "k"), "k25rkt3u6e");
        assert_eq!(make_v2_address("82", "k"), "kt7h1fvtp8");
        assert_eq!(make_v2_address("83", "k"), "k2f50jauzs");
        assert_eq!(make_v2_address("84", "k"), "ku419iels5");
        assert_eq!(make_v2_address("85", "k"), "k7fnnfng5q");
        assert_eq!(make_v2_address("86", "k"), "kgh7b5h9fw");
        assert_eq!(make_v2_address("87", "k"), "kpwafxhsyh");
        assert_eq!(make_v2_address("88", "k"), "krnbtr8w8g");
        assert_eq!(make_v2_address("89", "k"), "kbmlh4hjwh");
        assert_eq!(make_v2_address("90", "k"), "kt0xdih5vk");
        assert_eq!(make_v2_address("91", "k"), "k6h71t7cak");
        assert_eq!(make_v2_address("92", "k"), "kafzait78z");
        assert_eq!(make_v2_address("93", "k"), "kk845fmb3d");
        assert_eq!(make_v2_address("94", "k"), "kjrthr5kqm");
        assert_eq!(make_v2_address("95", "k"), "kklv52fp7c");
        assert_eq!(make_v2_address("96", "k"), "kxeg7jiaea");
        assert_eq!(make_v2_address("97", "k"), "kul8kjp5il");
        assert_eq!(make_v2_address("98", "k"), "k7af9ujh1n");
        assert_eq!(make_v2_address("99", "k"), "kwab593p5f");
        assert_eq!(make_v2_address("100", "k"), "krctdix0sq");
        assert_eq!(make_v2_address("101", "k"), "kgnyula9h8");
        assert_eq!(make_v2_address("102", "k"), "kxg0aduwvx");
        assert_eq!(make_v2_address("103", "k"), "kzjyuwk0rt");
        assert_eq!(make_v2_address("104", "k"), "kmgbq8e7dm");
        assert_eq!(make_v2_address("105", "k"), "k74iyrz4gj");
        assert_eq!(make_v2_address("106", "k"), "kyer67u70a");
        assert_eq!(make_v2_address("107", "k"), "kj5ncxwpba");
        assert_eq!(make_v2_address("108", "k"), "kp9gapmnjb");
        assert_eq!(make_v2_address("109", "k"), "kcrzn7elnb");
        assert_eq!(make_v2_address("110", "k"), "kqxc8t5pk5");
        assert_eq!(make_v2_address("111", "k"), "kl0ety2ved");
        assert_eq!(make_v2_address("112", "k"), "k1i28vwzy2");
        assert_eq!(make_v2_address("113", "k"), "kd3nk00lr2");
        assert_eq!(make_v2_address("114", "k"), "kusjee0fsa");
        assert_eq!(make_v2_address("115", "k"), "ktoq7zhg6b");
        assert_eq!(make_v2_address("116", "k"), "kpe41x1d8q");
        assert_eq!(make_v2_address("117", "k"), "kgmizusgje");
        assert_eq!(make_v2_address("118", "k"), "ktubqq1z0g");
        assert_eq!(make_v2_address("119", "k"), "kknh2g0fpu");
        assert_eq!(make_v2_address("120", "k"), "kkotnnlnrk");
        assert_eq!(make_v2_address("121", "k"), "k374y2zcoh");
        assert_eq!(make_v2_address("122", "k"), "kp4ya34bdr");
        assert_eq!(make_v2_address("123", "k"), "k87ztrc3ux");
        assert_eq!(make_v2_address("124", "k"), "k1xzs3pp60");
        assert_eq!(make_v2_address("125", "k"), "k83oqmgeof");
        assert_eq!(make_v2_address("126", "k"), "kikqflxnmt");
        assert_eq!(make_v2_address("127", "k"), "k8letwm0rc");
        assert_eq!(make_v2_address("128", "k"), "k2edtlefz3");
        assert_eq!(make_v2_address("129", "k"), "kpkgrigsi0");
        assert_eq!(make_v2_address("130", "k"), "kygnstc84s");
        assert_eq!(make_v2_address("131", "k"), "k6bpuud2b3");
        assert_eq!(make_v2_address("132", "k"), "kz62bcfdg9");
        assert_eq!(make_v2_address("133", "k"), "knlz3z9ixx");
        assert_eq!(make_v2_address("134", "k"), "ktnz4j43la");
        assert_eq!(make_v2_address("135", "k"), "k5wuk0bywe");
        assert_eq!(make_v2_address("136", "k"), "kieqagr7kf");
        assert_eq!(make_v2_address("137", "k"), "kcw4tg07rd");
        assert_eq!(make_v2_address("138", "k"), "kzrtut9nfw");
        assert_eq!(make_v2_address("139", "k"), "ke9oen8jm4");
        assert_eq!(make_v2_address("140", "k"), "kxzee8zr3e");
        assert_eq!(make_v2_address("141", "k"), "kc2j8sjyq5");
        assert_eq!(make_v2_address("142", "k"), "kworv9lvs4");
        assert_eq!(make_v2_address("143", "k"), "kaohp4p3si");
        assert_eq!(make_v2_address("144", "k"), "k6ieq61ain");
        assert_eq!(make_v2_address("145", "k"), "k2vmz08i0t");
        assert_eq!(make_v2_address("146", "k"), "kis0leeqa9");
        assert_eq!(make_v2_address("147", "k"), "khjrjtvw1r");
        assert_eq!(make_v2_address("148", "k"), "k6qpovbz0i");
        assert_eq!(make_v2_address("149", "k"), "kxhqofy1e2");
        assert_eq!(make_v2_address("150", "k"), "klcbpxbfug");
        assert_eq!(make_v2_address("151", "k"), "kkijeer13l");
        assert_eq!(make_v2_address("152", "k"), "kyo8u0zx8o");
        assert_eq!(make_v2_address("153", "k"), "kekc1d227m");
        assert_eq!(make_v2_address("154", "k"), "kqlapwke4f");
        assert_eq!(make_v2_address("155", "k"), "kd471hywzm");
        assert_eq!(make_v2_address("156", "k"), "kz5f9y60a8");
        assert_eq!(make_v2_address("157", "k"), "kobk5ffcu4");
        assert_eq!(make_v2_address("158", "k"), "kvxmvldcqa");
        assert_eq!(make_v2_address("159", "k"), "kywb30sayh");
        assert_eq!(make_v2_address("160", "k"), "keq28qcm51");
        assert_eq!(make_v2_address("161", "k"), "kcp5rdxxfh");
        assert_eq!(make_v2_address("162", "k"), "kcog2mtlvz");
        assert_eq!(make_v2_address("163", "k"), "k8pxe2fexf");
        assert_eq!(make_v2_address("164", "k"), "khijb7z7a2");
        assert_eq!(make_v2_address("165", "k"), "kvlmdmahqi");
        assert_eq!(make_v2_address("166", "k"), "kep6stnzz1");
        assert_eq!(make_v2_address("167", "k"), "kp1wnoz7iy");
        assert_eq!(make_v2_address("168", "k"), "khsl1q1c6i");
        assert_eq!(make_v2_address("169", "k"), "kplerx9o2r");
        assert_eq!(make_v2_address("170", "k"), "knh9tz0wdk");
        assert_eq!(make_v2_address("171", "k"), "khcf3cuksh");
        assert_eq!(make_v2_address("172", "k"), "kiz5u6qfq2");
        assert_eq!(make_v2_address("173", "k"), "k8l6dr8j1m");
        assert_eq!(make_v2_address("174", "k"), "kvwfjf5b8w");
        assert_eq!(make_v2_address("175", "k"), "kndce8228g");
        assert_eq!(make_v2_address("176", "k"), "ko5zt1og4l");
        assert_eq!(make_v2_address("177", "k"), "kgmvepb2f3");
        assert_eq!(make_v2_address("178", "k"), "kt0pswyupz");
        assert_eq!(make_v2_address("179", "k"), "kgeu5nsesx");
        assert_eq!(make_v2_address("180", "k"), "keleokm7gq");
        assert_eq!(make_v2_address("181", "k"), "k1nryeyqur");
        assert_eq!(make_v2_address("182", "k"), "kovbmzueum");
        assert_eq!(make_v2_address("183", "k"), "k032rq73k8");
        assert_eq!(make_v2_address("184", "k"), "kq4eejhcum");
        assert_eq!(make_v2_address("185", "k"), "kefi33v46y");
        assert_eq!(make_v2_address("186", "k"), "kpkdrkk4nk");
        assert_eq!(make_v2_address("187", "k"), "kse84eze5t");
        assert_eq!(make_v2_address("188", "k"), "k5ay159riy");
        assert_eq!(make_v2_address("189", "k"), "k0gjbheccf");
        assert_eq!(make_v2_address("190", "k"), "k0ttem3ky5");
        assert_eq!(make_v2_address("191", "k"), "k6pxz9mm82");
        assert_eq!(make_v2_address("192", "k"), "k8b21r6hsy");
        assert_eq!(make_v2_address("193", "k"), "kdlb1iqbt0");
        assert_eq!(make_v2_address("194", "k"), "kijwh160j6");
        assert_eq!(make_v2_address("195", "k"), "kuef4g2p4r");
        assert_eq!(make_v2_address("196", "k"), "kbjamows1q");
        assert_eq!(make_v2_address("197", "k"), "kx6tg35r44");
        assert_eq!(make_v2_address("198", "k"), "kwx98pkwc0");
        assert_eq!(make_v2_address("199", "k"), "kwomw3gsfs");
        assert_eq!(make_v2_address("200", "k"), "ka1vjotxop");
        assert_eq!(make_v2_address("201", "k"), "kf1e52ni55");
        assert_eq!(make_v2_address("202", "k"), "ka87dfo9uj");
        assert_eq!(make_v2_address("203", "k"), "kiu2xfouji");
        assert_eq!(make_v2_address("204", "k"), "krbmkwkqkg");
        assert_eq!(make_v2_address("205", "k"), "keyq7ddnmx");
        assert_eq!(make_v2_address("206", "k"), "kpv5hefz9b");
        assert_eq!(make_v2_address("207", "k"), "kckwypeqe5");
        assert_eq!(make_v2_address("208", "k"), "k1z6d3p5d2");
        assert_eq!(make_v2_address("209", "k"), "kpj5gtgn6g");
        assert_eq!(make_v2_address("210", "k"), "k6ec4vnvzz");
        assert_eq!(make_v2_address("211", "k"), "kcouh6u1n2");
        assert_eq!(make_v2_address("212", "k"), "ka1xld041k");
        assert_eq!(make_v2_address("213", "k"), "k72qmjd9pb");
        assert_eq!(make_v2_address("214", "k"), "k0ibwhgemg");
        assert_eq!(make_v2_address("215", "k"), "kofiyejdeu");
        assert_eq!(make_v2_address("216", "k"), "kk1jjkdocu");
        assert_eq!(make_v2_address("217", "k"), "kzyhpv1wkv");
        assert_eq!(make_v2_address("218", "k"), "k6l5lskinq");
        assert_eq!(make_v2_address("219", "k"), "k67zpllvt8");
        assert_eq!(make_v2_address("220", "k"), "kdsvyececa");
        assert_eq!(make_v2_address("221", "k"), "k85eixj8t7");
        assert_eq!(make_v2_address("222", "k"), "kgmtocr4e3");
        assert_eq!(make_v2_address("223", "k"), "kdi07cwjiq");
        assert_eq!(make_v2_address("224", "k"), "kd0xce30xz");
        assert_eq!(make_v2_address("225", "k"), "kmh9yujjlu");
        assert_eq!(make_v2_address("226", "k"), "kt68d7c0wf");
        assert_eq!(make_v2_address("227", "k"), "k9rbe6yqhx");
        assert_eq!(make_v2_address("228", "k"), "kt0x4ior7o");
        assert_eq!(make_v2_address("229", "k"), "k0u84347fw");
        assert_eq!(make_v2_address("230", "k"), "k7dpgv7c86");
        assert_eq!(make_v2_address("231", "k"), "kaubgs97d9");
        assert_eq!(make_v2_address("232", "k"), "kdhsmkcwyk");
        assert_eq!(make_v2_address("233", "k"), "ke5ukpwebn");
        assert_eq!(make_v2_address("234", "k"), "k0pngtjeqy");
        assert_eq!(make_v2_address("235", "k"), "kza0eqyivb");
        assert_eq!(make_v2_address("236", "k"), "kqg0n9m7e8");
        assert_eq!(make_v2_address("237", "k"), "k5f4n7xap7");
        assert_eq!(make_v2_address("238", "k"), "konc1fjkmt");
        assert_eq!(make_v2_address("239", "k"), "kczj6op2wh");
        assert_eq!(make_v2_address("240", "k"), "kb9bp2xe2o");
        assert_eq!(make_v2_address("241", "k"), "krdkxx8zfr");
        assert_eq!(make_v2_address("242", "k"), "k9dht7f9du");
        assert_eq!(make_v2_address("243", "k"), "kzre959qxs");
        assert_eq!(make_v2_address("244", "k"), "k6bjxnor5w");
        assert_eq!(make_v2_address("245", "k"), "k9su2kluem");
        assert_eq!(make_v2_address("246", "k"), "kkto3bix1k");
        assert_eq!(make_v2_address("247", "k"), "kxapfe8a0e");
        assert_eq!(make_v2_address("248", "k"), "kjftqku8v2");
        assert_eq!(make_v2_address("249", "k"), "kwtr1e21sx");
        assert_eq!(make_v2_address("250", "k"), "k9h1metrcq");
        assert_eq!(make_v2_address("251", "k"), "kcq4xsm25x");
        assert_eq!(make_v2_address("252", "k"), "km5he4bt6e");
        assert_eq!(make_v2_address("253", "k"), "k5th9ei16x");
        assert_eq!(make_v2_address("254", "k"), "ke8qwgrod8");
        assert_eq!(make_v2_address("255", "k"), "kke7yjtadq");
        assert_eq!(make_v2_address("256", "k"), "kqku9g2y2b");
        assert_eq!(make_v2_address("257", "k"), "k5bab3mdwq");
        assert_eq!(make_v2_address("258", "k"), "kjto9qapf2");
        assert_eq!(make_v2_address("259", "k"), "kspxw3ncvw");
        assert_eq!(make_v2_address("260", "k"), "kckdj1jdk0");
        assert_eq!(make_v2_address("261", "k"), "klcq939sx9");
        assert_eq!(make_v2_address("262", "k"), "kndm6vnvgw");
        assert_eq!(make_v2_address("263", "k"), "kr1wkkdmzw");
        assert_eq!(make_v2_address("264", "k"), "ky9y5i39is");
        assert_eq!(make_v2_address("265", "k"), "kf5l4nuzxx");
        assert_eq!(make_v2_address("266", "k"), "k0behekrpx");
        assert_eq!(make_v2_address("267", "k"), "kyl266fyt0");
        assert_eq!(make_v2_address("268", "k"), "k3lvsg91k2");
        assert_eq!(make_v2_address("269", "k"), "kve2fzq4eo");
        assert_eq!(make_v2_address("270", "k"), "kn9lel2a00");
        assert_eq!(make_v2_address("271", "k"), "kigjpckrkj");
        assert_eq!(make_v2_address("272", "k"), "kxcsso5c7m");
        assert_eq!(make_v2_address("273", "k"), "k5wam88uq9");
        assert_eq!(make_v2_address("274", "k"), "kazvtx16ak");
        assert_eq!(make_v2_address("275", "k"), "kkyxeebsb2");
        assert_eq!(make_v2_address("276", "k"), "kjoplxmupb");
        assert_eq!(make_v2_address("277", "k"), "kzydwa1w6u");
        assert_eq!(make_v2_address("278", "k"), "k2zebxi5zn");
        assert_eq!(make_v2_address("279", "k"), "kbay6veadw");
        assert_eq!(make_v2_address("280", "k"), "kx3k0nh0t3");
        assert_eq!(make_v2_address("281", "k"), "k8p7jqkye6");
        assert_eq!(make_v2_address("282", "k"), "kxxmndcee8");
        assert_eq!(make_v2_address("283", "k"), "kjwq364l99");
        assert_eq!(make_v2_address("284", "k"), "k0ejl84ta1");
        assert_eq!(make_v2_address("285", "k"), "k7u0k50hy2");
        assert_eq!(make_v2_address("286", "k"), "kmcveyfmj8");
        assert_eq!(make_v2_address("287", "k"), "k1qyv3eg8s");
        assert_eq!(make_v2_address("288", "k"), "kcya77hjda");
        assert_eq!(make_v2_address("289", "k"), "kt57lb76be");
        assert_eq!(make_v2_address("290", "k"), "k35lg5kxds");
        assert_eq!(make_v2_address("291", "k"), "k64q8ezqc9");
        assert_eq!(make_v2_address("292", "k"), "kakjdk810g");
        assert_eq!(make_v2_address("293", "k"), "kynhxopcfj");
        assert_eq!(make_v2_address("294", "k"), "kqicc9hr49");
        assert_eq!(make_v2_address("295", "k"), "kazwjwlb30");
        assert_eq!(make_v2_address("296", "k"), "kqebd9o6sj");
        assert_eq!(make_v2_address("297", "k"), "k7jeedp1s7");
        assert_eq!(make_v2_address("298", "k"), "k1j08912n0");
        assert_eq!(make_v2_address("299", "k"), "kc843fjh4y");
        assert_eq!(make_v2_address("300", "k"), "k24allidu5");
        assert_eq!(make_v2_address("301", "k"), "k9hideg7nj");
        assert_eq!(make_v2_address("302", "k"), "kljow0pa1x");
        assert_eq!(make_v2_address("303", "k"), "k5q0sr5bnp");
        assert_eq!(make_v2_address("304", "k"), "kedms28jtt");
        assert_eq!(make_v2_address("305", "k"), "kge3uohbtc");
        assert_eq!(make_v2_address("306", "k"), "ki8120gxv7");
        assert_eq!(make_v2_address("307", "k"), "kof5dyf22g");
        assert_eq!(make_v2_address("308", "k"), "k5x422vyna");
        assert_eq!(make_v2_address("309", "k"), "kckgen6gtl");
        assert_eq!(make_v2_address("310", "k"), "k77pqhw81s");
        assert_eq!(make_v2_address("311", "k"), "kubddyq3ho");
        assert_eq!(make_v2_address("312", "k"), "kv6x8dw8og");
        assert_eq!(make_v2_address("313", "k"), "kan37hvpls");
        assert_eq!(make_v2_address("314", "k"), "kz9qgu0n2i");
        assert_eq!(make_v2_address("315", "k"), "kmcb1vyd26");
        assert_eq!(make_v2_address("316", "k"), "kcrj3hvkaj");
        assert_eq!(make_v2_address("317", "k"), "k7wk8ep1ek");
        assert_eq!(make_v2_address("318", "k"), "k785rvqchy");
        assert_eq!(make_v2_address("319", "k"), "kzzjjw2c27");
        assert_eq!(make_v2_address("320", "k"), "k0zeb05xpi");
        assert_eq!(make_v2_address("321", "k"), "kbvh9s776t");
        assert_eq!(make_v2_address("322", "k"), "ku2q9efyn8");
        assert_eq!(make_v2_address("323", "k"), "kfzsas2rlc");
        assert_eq!(make_v2_address("324", "k"), "k3owf2ki1m");
        assert_eq!(make_v2_address("325", "k"), "ktv5jx5brp");
        assert_eq!(make_v2_address("326", "k"), "kw9wc1ytw8");
        assert_eq!(make_v2_address("327", "k"), "kcmj2ttuu3");
        assert_eq!(make_v2_address("328", "k"), "k6rfh0q4iv");
        assert_eq!(make_v2_address("329", "k"), "kws36f8lgg");
        assert_eq!(make_v2_address("330", "k"), "kmboq56wtr");
        assert_eq!(make_v2_address("331", "k"), "km81bj59vl");
        assert_eq!(make_v2_address("332", "k"), "kuwrri9yf1");
        assert_eq!(make_v2_address("333", "k"), "killry8iwc");
        assert_eq!(make_v2_address("334", "k"), "kon66rjutd");
        assert_eq!(make_v2_address("335", "k"), "kxjb5jvu2h");
        assert_eq!(make_v2_address("336", "k"), "k2oakbaq4k");
        assert_eq!(make_v2_address("337", "k"), "kq15hw8tqs");
        assert_eq!(make_v2_address("338", "k"), "k0j6xv3bl4");
        assert_eq!(make_v2_address("339", "k"), "kxsr24s5ds");
        assert_eq!(make_v2_address("340", "k"), "kjywbefd5i");
        assert_eq!(make_v2_address("341", "k"), "klc6xny3mq");
        assert_eq!(make_v2_address("342", "k"), "k2cvw1vh3b");
        assert_eq!(make_v2_address("343", "k"), "k30m6uxr19");
        assert_eq!(make_v2_address("344", "k"), "knc8eztgl9");
        assert_eq!(make_v2_address("345", "k"), "kehjc3v4hb");
        assert_eq!(make_v2_address("346", "k"), "kgba49x70l");
        assert_eq!(make_v2_address("347", "k"), "kjmxbtkkug");
        assert_eq!(make_v2_address("348", "k"), "kywi88dcyg");
        assert_eq!(make_v2_address("349", "k"), "kl6ase0tcd");
        assert_eq!(make_v2_address("350", "k"), "kuqqq2dnwi");
        assert_eq!(make_v2_address("351", "k"), "kfifpmz0n8");
        assert_eq!(make_v2_address("352", "k"), "k60lrz5zad");
        assert_eq!(make_v2_address("353", "k"), "k6l8xu3lao");
        assert_eq!(make_v2_address("354", "k"), "k7ktiw4wxe");
        assert_eq!(make_v2_address("355", "k"), "kt1xsbtr0l");
        assert_eq!(make_v2_address("356", "k"), "kd201uihs1");
        assert_eq!(make_v2_address("357", "k"), "kk502t3dp4");
        assert_eq!(make_v2_address("358", "k"), "k3c7jtlhpf");
        assert_eq!(make_v2_address("359", "k"), "ks1jzfm6gk");
        assert_eq!(make_v2_address("360", "k"), "k6158pjvgk");
        assert_eq!(make_v2_address("361", "k"), "ksmlhrmeue");
        assert_eq!(make_v2_address("362", "k"), "ku69svuipa");
        assert_eq!(make_v2_address("363", "k"), "kmkxhskg26");
        assert_eq!(make_v2_address("364", "k"), "kyjzsv3bwk");
        assert_eq!(make_v2_address("365", "k"), "kw0uzyy6np");
        assert_eq!(make_v2_address("366", "k"), "kr8t24easf");
        assert_eq!(make_v2_address("367", "k"), "kfmkjlx842");
        assert_eq!(make_v2_address("368", "k"), "kkv8yakxw6");
        assert_eq!(make_v2_address("369", "k"), "k9be6fc4pp");
        assert_eq!(make_v2_address("370", "k"), "kn8xaxjodb");
        assert_eq!(make_v2_address("371", "k"), "k6irq0kv0v");
        assert_eq!(make_v2_address("372", "k"), "k1e3ujk6wq");
        assert_eq!(make_v2_address("373", "k"), "ku47ukdpw5");
        assert_eq!(make_v2_address("374", "k"), "keqz1zjoif");
        assert_eq!(make_v2_address("375", "k"), "k5qb8odmpv");
        assert_eq!(make_v2_address("376", "k"), "k707ttg07b");
        assert_eq!(make_v2_address("377", "k"), "kfovy1o8z8");
        assert_eq!(make_v2_address("378", "k"), "kdgztdpdb3");
        assert_eq!(make_v2_address("379", "k"), "k07w0k5mdr");
        assert_eq!(make_v2_address("380", "k"), "k9erfead9d");
        assert_eq!(make_v2_address("381", "k"), "kewucuhjh8");
        assert_eq!(make_v2_address("382", "k"), "kmg960s5xh");
        assert_eq!(make_v2_address("383", "k"), "kivqvc1k1q");
        assert_eq!(make_v2_address("384", "k"), "kqgjjbogq5");
        assert_eq!(make_v2_address("385", "k"), "k1u1l8rog0");
        assert_eq!(make_v2_address("386", "k"), "k6i2ohgv1k");
        assert_eq!(make_v2_address("387", "k"), "kezylhmo0r");
        assert_eq!(make_v2_address("388", "k"), "kjbxak2z0w");
        assert_eq!(make_v2_address("389", "k"), "koqao9i3ca");
        assert_eq!(make_v2_address("390", "k"), "k70zo6oull");
        assert_eq!(make_v2_address("391", "k"), "k0f8c6i24g");
        assert_eq!(make_v2_address("392", "k"), "k26h2pyk3x");
        assert_eq!(make_v2_address("393", "k"), "kwy5b2qpw5");
        assert_eq!(make_v2_address("394", "k"), "k9z3wfvp9y");
        assert_eq!(make_v2_address("395", "k"), "keuvmjvdok");
        assert_eq!(make_v2_address("396", "k"), "kheym5ydtb");
        assert_eq!(make_v2_address("397", "k"), "kyn0qp9nme");
        assert_eq!(make_v2_address("398", "k"), "kozjb3e600");
        assert_eq!(make_v2_address("399", "k"), "k6paf8j0v5");
        assert_eq!(make_v2_address("400", "k"), "kd9hd8jet5");
        assert_eq!(make_v2_address("401", "k"), "kxk5h8qlj3");
        assert_eq!(make_v2_address("402", "k"), "kxfeso66vg");
        assert_eq!(make_v2_address("403", "k"), "kdsmnm4chy");
        assert_eq!(make_v2_address("404", "k"), "k5eegm3p2u");
        assert_eq!(make_v2_address("405", "k"), "k9b091ya6f");
        assert_eq!(make_v2_address("406", "k"), "ktzhe87ubl");
        assert_eq!(make_v2_address("407", "k"), "ksep1fa61j");
        assert_eq!(make_v2_address("408", "k"), "kwrolpzeqn");
        assert_eq!(make_v2_address("409", "k"), "k8qe2w7zap");
        assert_eq!(make_v2_address("410", "k"), "kvg59nleox");
        assert_eq!(make_v2_address("411", "k"), "knflk5xj7r");
        assert_eq!(make_v2_address("412", "k"), "ksxe8m5vgj");
        assert_eq!(make_v2_address("413", "k"), "k6tb6b58w5");
        assert_eq!(make_v2_address("414", "k"), "kgisov53d9");
        assert_eq!(make_v2_address("415", "k"), "k85wf6al4h");
        assert_eq!(make_v2_address("416", "k"), "kg7vs5ay26");
        assert_eq!(make_v2_address("417", "k"), "kto8fon2hf");
        assert_eq!(make_v2_address("418", "k"), "kcguuth9iu");
        assert_eq!(make_v2_address("419", "k"), "kx1ma958d6");
        assert_eq!(make_v2_address("420", "k"), "kjlia7t17w");
        assert_eq!(make_v2_address("421", "k"), "krf83tea6g");
        assert_eq!(make_v2_address("422", "k"), "k70h51q19p");
        assert_eq!(make_v2_address("423", "k"), "kbhntvkway");
        assert_eq!(make_v2_address("424", "k"), "ktdjmux1y8");
        assert_eq!(make_v2_address("425", "k"), "ko9j7pymsh");
        assert_eq!(make_v2_address("426", "k"), "kglxiia3lf");
        assert_eq!(make_v2_address("427", "k"), "kd0l7m0ts9");
        assert_eq!(make_v2_address("428", "k"), "kzu036y23j");
        assert_eq!(make_v2_address("429", "k"), "ktujd2ax0f");
        assert_eq!(make_v2_address("430", "k"), "kmthykdyal");
        assert_eq!(make_v2_address("431", "k"), "ks0q4mn7k2");
        assert_eq!(make_v2_address("432", "k"), "khbyuw79ki");
        assert_eq!(make_v2_address("433", "k"), "kr9aphloq5");
        assert_eq!(make_v2_address("434", "k"), "kegtj6z2hf");
        assert_eq!(make_v2_address("435", "k"), "krf5y3e49u");
        assert_eq!(make_v2_address("436", "k"), "kpt6zkw32n");
        assert_eq!(make_v2_address("437", "k"), "kz4x2e1z9v");
        assert_eq!(make_v2_address("438", "k"), "kxnzhfqwgi");
        assert_eq!(make_v2_address("439", "k"), "ksuc9u0o2g");
        assert_eq!(make_v2_address("440", "k"), "k7tevar8t7");
        assert_eq!(make_v2_address("441", "k"), "k1c40riqeb");
        assert_eq!(make_v2_address("442", "k"), "kizej7ve1i");
        assert_eq!(make_v2_address("443", "k"), "keheypinlw");
        assert_eq!(make_v2_address("444", "k"), "kempj8gszx");
        assert_eq!(make_v2_address("445", "k"), "kze8wndm5m");
        assert_eq!(make_v2_address("446", "k"), "kvtvtmfnbe");
        assert_eq!(make_v2_address("447", "k"), "kixq88hlue");
        assert_eq!(make_v2_address("448", "k"), "kvdihgz2f5");
        assert_eq!(make_v2_address("449", "k"), "kg4ct9jhmu");
        assert_eq!(make_v2_address("450", "k"), "ke8w8detyl");
        assert_eq!(make_v2_address("451", "k"), "ki8gov8pge");
        assert_eq!(make_v2_address("452", "k"), "ki4n2l8h22");
        assert_eq!(make_v2_address("453", "k"), "kdieb5dxmm");
        assert_eq!(make_v2_address("454", "k"), "k5ufb6m94e");
        assert_eq!(make_v2_address("455", "k"), "k4fogv2k5d");
        assert_eq!(make_v2_address("456", "k"), "kwcl383iho");
        assert_eq!(make_v2_address("457", "k"), "kd8whqxbzj");
        assert_eq!(make_v2_address("458", "k"), "knjr2qzfhi");
        assert_eq!(make_v2_address("459", "k"), "kn7kjr9iul");
        assert_eq!(make_v2_address("460", "k"), "k4kdrxaicw");
        assert_eq!(make_v2_address("461", "k"), "k8q6qw3bsc");
        assert_eq!(make_v2_address("462", "k"), "kf36yzuz7a");
        assert_eq!(make_v2_address("463", "k"), "kq5s6lv063");
        assert_eq!(make_v2_address("464", "k"), "ksyaorspau");
        assert_eq!(make_v2_address("465", "k"), "kz2co7tonh");
        assert_eq!(make_v2_address("466", "k"), "kfqy9k69e0");
        assert_eq!(make_v2_address("467", "k"), "k2duxfb01g");
        assert_eq!(make_v2_address("468", "k"), "kh6cnni5zg");
        assert_eq!(make_v2_address("469", "k"), "k5mmku9gba");
        assert_eq!(make_v2_address("470", "k"), "k3x7dyjqvf");
        assert_eq!(make_v2_address("471", "k"), "kmtva7hgip");
        assert_eq!(make_v2_address("472", "k"), "k7wms0j021");
        assert_eq!(make_v2_address("473", "k"), "ktqmv0ryke");
        assert_eq!(make_v2_address("474", "k"), "ktzb5r4gx5");
        assert_eq!(make_v2_address("475", "k"), "kyb78wlusb");
        assert_eq!(make_v2_address("476", "k"), "k4u3e02ctg");
        assert_eq!(make_v2_address("477", "k"), "kw500krdm5");
        assert_eq!(make_v2_address("478", "k"), "khxdaeaiei");
        assert_eq!(make_v2_address("479", "k"), "kfxmxar2mu");
        assert_eq!(make_v2_address("480", "k"), "kka0nojh98");
        assert_eq!(make_v2_address("481", "k"), "kk3vec3iec");
        assert_eq!(make_v2_address("482", "k"), "ke8a7m24fo");
        assert_eq!(make_v2_address("483", "k"), "kd9hb0zi7w");
        assert_eq!(make_v2_address("484", "k"), "kedcb1om4o");
        assert_eq!(make_v2_address("485", "k"), "kiaxpot49o");
        assert_eq!(make_v2_address("486", "k"), "k145p4prm2");
        assert_eq!(make_v2_address("487", "k"), "k63fp9gic2");
        assert_eq!(make_v2_address("488", "k"), "kml61hvyzq");
        assert_eq!(make_v2_address("489", "k"), "kii18hcy7i");
        assert_eq!(make_v2_address("490", "k"), "kh78genprs");
        assert_eq!(make_v2_address("491", "k"), "k3mou76fll");
        assert_eq!(make_v2_address("492", "k"), "ka8th0vkah");
        assert_eq!(make_v2_address("493", "k"), "kapksxsy7y");
        assert_eq!(make_v2_address("494", "k"), "ksh9pd3tr1");
        assert_eq!(make_v2_address("495", "k"), "k2tne29egl");
        assert_eq!(make_v2_address("496", "k"), "kous55xqd9");
        assert_eq!(make_v2_address("497", "k"), "k6mv6wwngi");
        assert_eq!(make_v2_address("498", "k"), "kd6ce07gw8");
        assert_eq!(make_v2_address("499", "k"), "ks40hchnc8");
    }
}
